services:
  grafana:
    container_name: monitoring-grafana
    image: grafana/grafana:latest
    restart: unless-stopped
    network_mode: host
    user: "472"
    env_file:
      - ./grafana/.env
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus

  prometheus:
    container_name: monitoring-prometheus
    image: prom/prometheus:latest
    restart: unless-stopped
    network_mode: host
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=180d'
      - '--storage.tsdb.retention.size=10GB'
      - '--storage.tsdb.wal-compression'
      - '--web.enable-lifecycle'
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus:/etc/prometheus:ro
    depends_on:
      - cadvisor
      - node-exporter

  node-exporter:
    container_name: monitoring-node-exporter
    image: prom/node-exporter:latest
    restart: unless-stopped
    network_mode: host
    pid: host
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --path.rootfs=/host
      - --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($|/)
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host:ro,rslave

  cadvisor:
    container_name: monitoring-cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    restart: unless-stopped
    network_mode: host
    privileged: true
    command:
      - '--docker_only=true'
      - '--housekeeping_interval=30s'
      - '--store_container_labels=false'
    devices:
      - /dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk:/dev/disk:ro
      - /etc/machine-id:/etc/machine-id:ro

volumes:
  grafana-data:
  prometheus-data:
